name: Basic Workflow

on: 
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'World'
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
jobs: 

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run a simple command
        run: echo "Hello, World"
      
      
      
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up Java
        uses: actions/setup-java@v3  
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Compile HelloWorld
        run: javac HelloWorld.java

      - name: Run HelloWorld
        run: java HelloWorld
