name: Deploy JS to Vercel

on:
  push:
    branches: main

jobs:
  integrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Save Vercel CLI
        run: echo "Vercel CLI installed" > vercel.txt
       
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vercel-cli-status
          path: vercel.txt
          
  deploy:
    needs: integrate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: vercel-cli-status

      - name: Install Vercel CLI (if not present)
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}